updates

diff --git a/Deps/mp4v2/mp4v2.SlackBuild b/Deps/mp4v2/mp4v2.SlackBuild
--- a/Deps/mp4v2/mp4v2.SlackBuild
+++ b/Deps/mp4v2/mp4v2.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Generated by Alien's SlackBuild Toolkit: http://slackware.com/~alien/AST
 # Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015  Eric Hameleers, Eindhoven, Netherlands
-# Copyright 2015-2016  Thorn Inurcide thorninurcide@gmail.com
+# Copyright 2015-2016  Thorn inurcide thorninurcide@gmail.com
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -22,35 +22,22 @@
 #   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 #   SUCH DAMAGE.
 
-# Heavily influenced by the SBo build script
-# Copyright (c) 2007  Alex Lysenka <me@alkos333.net>
-# Copyright (c) 2012  Vliegendehuiskat
-# Copyright (c) 2014-2015  Matteo Bernardini <ponce@slackbuilds.org>
-# All rights reserved.
-
-PRGNAM=speex
-PRGNAME=speexdsp
-VERSION=${VERSION:-1.2rc2}
-VER=${VER:-1.2rc3}
+PRGNAM=mp4v2
+VERSION=${VERSION:-2.0.0}
 BUILD=${BUILD:-1}
-TAG=${TAG:-_thorn}
+TAG=${TAG:-_tde}
 
-DOCS="AUTHORS ChangeLog* COPYING NEWS README* TODO"
+DOCS="COPYING README*"
 
 # Where do we look for sources?
 SRCDIR=$(cd $(dirname $0); pwd)
 
-# Place to build (TMP) package (PKG) and output (OUTPUT) the program:
 TMP=${TMP:-/tmp/build}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-# Input URL: http://downloads.xiph.org/releases/speex/speex-1.2rc2.tar.gz
-SOURCE[0]="$SRCDIR/${PRGNAM}-${VERSION}.tar.gz"
-SRCURL[0]="http://downloads.xiph.org/releases/${PRGNAM}/${PRGNAM}-${VERSION}.tar.gz"
-# Input URL: http://downloads.xiph.org/releases/speex/speexdsp-1.2rc3.tar.gz
-SOURCE[1]="$SRCDIR/${PRGNAME}-${VER}.tar.gz"
-SRCURL[1]="http://downloads.xiph.org/releases/${PRGNAM}/${PRGNAME}-${VER}.tar.gz"
+SOURCE="$SRCDIR/${PRGNAM}-${VERSION}.tar.bz2"
+SRCURL="http://mp4v2.googlecode.com/files/${PRGNAM}-${VERSION}.tar.bz2"
 
 # You can use your own private machine.conf file to overrule machine defaults:
 if [ -e $SRCDIR/machine.conf ]; then
@@ -107,34 +94,32 @@ _UMASK_=$(umask)
 umask 0022
 
 # Create working directories:
-mkdir -p $OUTPUT        
+mkdir -p $OUTPUT       
 mkdir -p $TMP/tmp-$PRGNAM 
-mkdir -p $PKG           
-rm -rf $PKG/*            
-rm -rf $TMP/tmp-$PRGNAM/* 
+mkdir -p $PKG            
+rm -rf $PKG/*             
+rm -rf $TMP/tmp-$PRGNAM/*
 rm -rf $OUTPUT/{checkout,configure,make,install,error,makepkg,patch}-$PRGNAM.log
 
 # Source file availability:
-for (( i = 0; i < ${#SOURCE[*]}; i++ )) ; do
-  if ! [ -f ${SOURCE[$i]} ]; then
-    echo "Source '$(basename ${SOURCE[$i]})' not available yet..."
-    # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
-    [ -w "$SRCDIR" ] || SOURCE[$i]="$OUTPUT/$(basename ${SOURCE[$i]})"
-    if [ -f ${SOURCE[$i]} ]; then echo "Ah, found it!"; continue; fi
-    if ! [ "x${SRCURL[$i]}" == "x" ]; then
-      echo "Will download file to $(dirname $SOURCE[$i])"
-      wget -nv -T 20 -O "${SOURCE[$i]}" "${SRCURL[$i]}" || true
-      if [ $? -ne 0 -o ! -s "${SOURCE[$i]}" ]; then
-        echo "Fail to download '$(basename ${SOURCE[$i]})'. Aborting the build."
-        mv -f "${SOURCE[$i]}" "${SOURCE[$i]}".FAIL
-        exit 1
-      fi
-    else
-      echo "File '$(basename ${SOURCE[$i]})' not available. Aborting the build."
+if ! [ -f ${SOURCE} ]; then
+  echo "Source '$(basename ${SOURCE})' not available yet..."
+  # Check if the $SRCDIR is writable at all - if not, download to $OUTPUT
+  [ -w "$SRCDIR" ] || SOURCE="$OUTPUT/$(basename $SOURCE)"
+  if [ -f ${SOURCE} ]; then echo "Ah, found it!"; continue; fi
+  if ! [ "x${SRCURL}" == "x" ]; then
+    echo "Will download file to $(dirname $SOURCE)"
+    wget -nv -T 20 -O "${SOURCE}" "${SRCURL}" || true
+    if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+      echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+      mv -f "${SOURCE}" "${SOURCE}".FAIL
       exit 1
     fi
+  else
+    echo "File '$(basename ${SOURCE})' not available... aborting the build."
+    exit 1
   fi
-done
+fi
 
 if [ "$P1" == "--download" ]; then
   echo "Download complete."
@@ -143,67 +128,23 @@ fi
 
 cd $TMP/tmp-$PRGNAM
 echo "Extracting the source archive(s) for $PRGNAM..."
-for (( i = 0; i < ${#SOURCE[*]}; i++ )) ; do
-  if $(file ${SOURCE[$i]} | grep -qi ": 7-zip"); then
-    7za x ${SOURCE[$i]}
-  elif $(file ${SOURCE[$i]} | grep -qi ": zip"); then
-    unzip ${SOURCE[$i]}
-  else
-    tar -xvf ${SOURCE[$i]}
-  fi
-done
+bsdtar -xvf ${SOURCE}
 
-cd ${PRGNAME}-${VER}
-chown -R root:root .
-chmod -R u+w,go+r-w,a+rX-st .
-
-# Thanks to SBo script for patch
-patch -p1 < $SRCDIR/speexdsp-fixbuilds-774c87d.patch
-autoreconf -fi
-
-LDFLAGS="$SLKLDFLAGS" \
-CXXFLAGS="$SLKCFLAGS" \
-CFLAGS="$SLKCFLAGS" \
-./configure \
-  --prefix=/usr \
-  --libdir=/usr/lib${LIBDIRSUFFIX} \
-  --mandir=/usr/man \
-  --docdir=/usr/doc/$PRGNAM-$VERSION/dsp \
-  --enable-static=no \
-  --enable-sse \
-  --build=$ARCH-slackware-linux
-
-make || exit 1
-make DESTDIR=$PKG install || exit 1
-
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a $DOCS $PKG/usr/doc/$PRGNAM-$VERSION || true
-cat $SRCDIR/$(basename $0) > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
-chown -R root:root $PKG/usr/doc/$PRGNAM-$VERSION
-find $PKG/usr/doc -type f -exec chmod 644 {} \;
-
-cd ..
 cd ${PRGNAM}-${VERSION}
 chown -R root:root .
 chmod -R u+w,go+r-w,a+rX-st .
 
-# Thanks to SBo again:
-sed -i 's/\r//' README.TI-DSP
-
 LDFLAGS="$SLKLDFLAGS" \
-CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
-SPEEXDSP_CFLAGS="-I$PKG/usr/include" \
-SPEEXDSP_LIBS="-L$PKG/usr/lib${LIBDIRSUFFIX} -lspeexdsp" \
+CFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --mandir=/usr/man \
   --docdir=/usr/doc/$PRGNAM-$VERSION \
-  --enable-static=no \
-  --enable-binaries \
-  --build=$ARCH-slackware-linux
-  
+  --disable-static \
+  --build=$ARCH-slackware-linux \
+
 make || exit 1
 make DESTDIR=$PKG install || exit 1
 
@@ -218,9 +159,6 @@ if [ -d $PKG/usr/man ]; then
   for i in $(find $PKG/usr/man -type l -name "*.?") ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 fi
 
-# Fix libspeex.la Thanks SBo script:
-sed -i "s|-L$PKG.*/lib${LIBDIRSUFFIX} ||" $PKG/usr/lib${LIBDIRSUFFIX}/libspeex.la
-
 find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
@@ -228,7 +166,7 @@ mkdir -p $PKG/install
 cat $SRCDIR/slack-desc > $PKG/install/slack-desc
 
 cd $PKG
-makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} 2>&1 | tee $OUTPUT/makepkg-${PRGNAM}.log
+makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} 
 cd $OUTPUT
 md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz}.md5
 cd -
