updates

diff --git a/Apps/abakus/abakus.SlackBuild b/Apps/abakus/abakus.SlackBuild
--- a/Apps/abakus/abakus.SlackBuild
+++ b/Apps/abakus/abakus.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Generated by Alien's SlackBuild Toolkit: http://slackware.com/~alien/AST
 # Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015  Eric Hameleers, Eindhoven, Netherlands
-# Copyright 2015-2016  Thorn inurcide
+# Copyright 2015-2016  Thorn Inurcide
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -22,12 +22,37 @@
 #   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 #   SUCH DAMAGE.
 
-PRGNAM=tdepim
+PRGNAM=abakus
 VERSION=${VERSION:-$TDEVERSION}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_tde}
 
-DOCS="MAINTAINERS README*"
+
+SlackDesc()
+{
+echo "
+# HOW TO EDIT THIS FILE:
+# The 'handy ruler' below makes it easier to edit a package description.  Line
+# up the first '|' above the ':' following the base package name, and the '|'
+# on the right side marks the last column you can put a character in.  You must
+# make exactly 11 lines for the formatting to be correct.  It's also
+# customary to leave one space after the ':'.
+
+$PRGNAM|-----handy-ruler------------------------------------------------------|
+$PRGNAM: $PRGNAM is a calculator designed with computer usability in mind.
+$PRGNAM: Instead of using your powerful computer to put a limited simulation
+$PRGNAM: of a calculator on-screen, $PRGNAM instead allows you to use your
+$PRGNAM: computer to its greater potential.
+$PRGNAM:
+$PRGNAM: Can be built and used with mpfr.
+$PRGNAM: Customizable precision up to 75 digits.
+$PRGNAM:
+$PRGNAM: Copy/paste or type in and evaluate complex expressions. Exponentiation
+$PRGNAM: is right-associative, for example:  (2^3)^2*e^4/pi  2^3^2*e^4/pi
+$PRGNAM:      [The answers given by $PRGNAM:  1112.26437907   8898.11503252]
+
+" > $PKG/install/slack-desc
+}
 
 source ../../get-source.sh
 
@@ -36,58 +61,36 @@ echo "
 Extracting the source from the ${PRGNAM} archive ..."
 tar -xf ${SOURCE}
 
+cd applications
 cd ${PRGNAM}
 
-# If libcaldav is installed, include it in the build for korganizer
-[[ $(ls /var/log/packages/libcaldav*) ]] 2>/dev/null && LCALDAV="ON"
+## add check for mpfr installed to set HAVE_MPFR, otherwise even if it is installed, abakus won't be built with mpfr
+sed -i 's|HAVE_INOTIFY )|HAVE_INOTIFY )\ncheck_include_file( mpfr.h HAVE_MPFR )|' ConfigureChecks.cmake
+## the linker can't find 'gmp' although it can find 'mpfr' and fails with:
+## [100%] Linking CXX executable abakus c++: error: gmp: No such file or directory
+## As libgmp is linked through libmpfr, do we really need libgmp here?
+sed -i 's|mpfr gmp|mpfr -lgmp|' src/CMakeLists.txt
+
+# list only files > zero bytes
+DOCS=$(for file in AUTHORS* ChangeLog* COPYING* FAQ* INSTALL* KNOWNBUGS* NEWS* README* TODO* *.lsm;do [[ -s $file ]] && ls -1 $file;done ) || true
 
 chown -R root:root .
 chmod -R u+w,go+r-w,a+rX-st .
 
 mkdir -p build-${PRGNAM}
 cd build-${PRGNAM}
+
   cmake \
-    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
+    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS $TQT_INCLUDE_PATH" \
     -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
-    -DCMAKE_C_FLAGS_RELEASE:STRING="$SLKCFLAGS" \
-    -DCMAKE_CXX_FLAGS_RELEASE:STRING="$SLKCFLAGS" \
-    -DCMAKE_BUILD_TYPE=Release \
     -DCMAKE_INSTALL_PREFIX=${INSTALL_TDE} \
-    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
-    -DSYSCONF_INSTALL_DIR="/etc/trinity" \
-    -DMAN_INSTALL_DIR=${INSTALL_TDE}/man \
-    -DWITH_ALL_OPTIONS="ON" \
-    -DWITH_GNOKII="OFF" \
-    -DWITH_CALDAV=${LCALDAV:-"OFF"} \
-    -DWITH_CARDDAV="OFF" \
-    -DBUILD_ALL="ON" \
-    -Wno-dev \
+    -DBUILD_DOC="ON" \
     ..
+
+
   make $NUMJOBS || exit 1
   make DESTDIR=$PKG install || exit 1
 cd -
-
-# Add this to the doinst.sh:
-mkdir -p $PKG/install
-cat <<EOINS >> $PKG/install/doinst.sh
-# Update the desktop database:
-if [ -x usr/bin/update-desktop-database ]; then
-  chroot . /usr/bin/update-desktop-database usr/share/applications > /dev/null 2>&1
-fi
-
-# Update hicolor theme cache:
-if [ -d usr/share/icons/hicolor ]; then
-  if [ -x /usr/bin/gtk-update-icon-cache ]; then
-    chroot . /usr/bin/gtk-update-icon-cache -f -t usr/share/icons/hicolor 1> /dev/null 2> /dev/null
-  fi
-fi
-
-# Update the mime database:
-if [ -x usr/bin/update-mime-database ]; then
-  chroot . /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
-fi
-
-EOINS
 
 mkdir -p $PKG${INSTALL_TDE}/doc/$PRGNAM-$VERSION
 cp -a $DOCS $PKG${INSTALL_TDE}/doc/$PRGNAM-$VERSION || true
@@ -99,14 +102,16 @@ find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 mkdir -p $PKG/install
-cat $SRCDIR/slack-desc > $PKG/install/slack-desc
+SlackDesc
+
 
 cd $PKG
 makepkg --linkadd y --chown n $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} 
 cd $OUTPUT
 md5sum ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz} > ${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.${PKGTYPE:-txz}.md5
 cd -
-cat $PKG/install/slack-desc | grep "^${PRGNAM}" > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txt
+cat $PKG/install/slack-desc | grep "^${PRGNAM}" | grep -v handy > $OUTPUT/${PRGNAM}-${VERSION}-${ARCH}-${BUILD}${TAG}.txt
 
 # Restore the original umask:
-umask ${_UMASK_} 
+umask ${_UMASK_}
+ 
